### ISSUE TITLE
display is just black

### ISSUE THREAD

**Issue by torst3n** [netzbasteln/MLX90640-Thermocam#3]
really like the thermocam project! 
I am trying to build it with the exact same hardware components linked in the readme. My problem is that i can't get the display working it is just black. I connected the pins like that:

![mlx90640 thermo cam_schem](https://user-images.githubusercontent.com/2260337/52380380-cc5d9e00-2a6d-11e9-85ba-ba176e3c15ee.png)

![mlx90640 thermo cam_bb](https://user-images.githubusercontent.com/2260337/52380365-c1a30900-2a6d-11e9-86c2-9de4e48945eb.png)

What did I do wrong ? 
If I can get it working I would be happy to create a pull request (with the corrected wiring) to add the schematic to the readme. 

Thanks for your help!

**Comment by hpd96** [comment]
Hi, würde noch LED mit 3,3 V verbinden :-) Dein Plan scheint richtig zu sein . vg

**Comment by torst3n** [comment]
> Hi, würde noch LED mit 3,3 V verbinden :-) Dein Plan scheint richtig zu sein . vg

Thanks for your help @hpd96 !! Now I have a white display. 
I got a graphicstest running from the examples so the display is not the problem. When I debug with println I can see that the min / max temperatures are set and no other errors occur.
Any Ideas ?

**Comment by hpd96** [comment]
Hi, use the user_setup.h of _this_ netzbasteln repo. Wunderbar vorkonfiguriert :-)
Overwrite the user_setup.h of TFT library !

2nd)
press [boot] again ?

My thermoCam working since yesterday ...

Great nova project !!

**Comment by torst3n** [comment]
Mine is now also working! Thanks. 

I totally missed that the user_setup.h of TFT_eSPI Library must be overwritten.
